---
- name: Create mixin directory
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  tags:
    - resolved

- name: Link resolver config
  when:
    - resolved_stub_listener
  notify:
    - Restart resolved
  ansible.builtin.file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    force: true
    state: link
  tags:
    - resolved

- name: Write resolver config
  when:
    - not resolved_stub_listener
  notify:
    - Restart resolved
  ansible.builtin.template:
    src: resolv.j2
    dest: /etc/resolv.conf
    force: true
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - resolved

- name: Mask dhcp config
  notify:
    - Restart resolved
  when:
    - resolved_dhcp_mask
  ansible.builtin.file:
    src: /dev/null
    dest: "/etc/systemd/resolved.conf.d/{{ resolved_dhcp_name }}"
    force: true
    state: link
  tags:
    - resolved

- name: Unmask dhcp config
  notify:
    - Restart resolved
  when:
    - not resolved_dhcp_mask
  ansible.builtin.file:
    path: "/etc/systemd/resolved.conf.d/{{ resolved_dhcp_name }}"
    state: absent
  tags:
    - resolved

- name: Write systemd config
  notify:
    - Restart resolved
  ansible.builtin.template:
    src: config.j2
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - resolved

- name: Start resolved service
  ansible.builtin.systemd:
    name: systemd-resolved
    state: started
    daemon_reload: true
    masked: false
    enabled: true
  tags:
    - resolved

...
